version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/investment
      - SECRET_KEY=SAYaq'*#|Pb_+v;~J2&SmTwx3s6rHc
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=investment
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
