"""Use Numeric for Prices

Revision ID: 42063fd5df95
Revises: 406e798f6e3f
Create Date: 2023-09-25 21:06:46.941639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42063fd5df95'
down_revision: Union[str, None] = '406e798f6e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    op.alter_column('stocks', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    op.drop_column('stocks', 'total_volume')
    op.alter_column('transactions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    op.alter_column('transactions', 'purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'purchase_price',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('transactions', 'price',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('stocks', sa.Column('total_volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('stocks', 'price',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('clients', 'balance',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
