"""Add purchase price for transactions

Revision ID: 5ac76883fe6b
Revises: 91d886e0d8a5
Create Date: 2023-09-24 15:26:05.069645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac76883fe6b'
down_revision: Union[str, None] = '91d886e0d8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('purchase_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'purchase_price')
    # ### end Alembic commands ###
