"""Add balance field to client table

Revision ID: 91d886e0d8a5
Revises: 6d67380c9806
Create Date: 2023-09-24 00:34:18.132128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d886e0d8a5'
down_revision: Union[str, None] = '6d67380c9806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'balance')
    # ### end Alembic commands ###
